ownerbilling2018/Models/OwnerBilling.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

ownerbilling2018/Controllers/OwnerBillingController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Mvc.Html;
using System.Data.SqlClient;
using System.Configuration;
using PagedList;
using PagedList.Mvc;
using System.IO;
using System.Net.Http;
using System.Web.Security;
using ownerbilling2018.Models;

namespace ownerbilling2018.Controllers
{
    public class OwnerBillingController : KPIController
    {
        private App_KPI_OwnerBillingEntities db = new App_KPI_OwnerBillingEntities();
        private App_KPI_OwnerBillingEntitiesRegion dbRegion = new App_KPI_OwnerBillingEntitiesRegion();
        private App_KPI_OwnerBillingEntitiesCompany dbCompany = new App_KPI_OwnerBillingEntitiesCompany();

        [HttpPost]
        [Authorize]
        public ActionResult Edit([Bind(Include = "OBSubWorkEstimate,OBIsCurrent,jobdescription,MMMCU,OBSeqNoId,OBApplicationNo,OBRequisitionDate,OBStatus,OBStatusDescription,OBSubmitDate,OBApproveDate,OBTotalEstimate,OBTotalFinal,KDOwnerPaymentReceivedDate,G4DueDate,OBUserName,OBDateAdd,OBDateChange,OBClarkWorkEstimate,OBOwnerRetentionEstimate, OBSubRetentionEstimate, OBSubWorkFinal, OBClarkWorkFinal, OBOwnerRetentionFinal, OBSubRetentionFinal, OBRemark")] spOwnerBilling_Result OB, string referrer, string buttontype)
        {
            if (TempData.Peek("KeyType") == null)
            {
                string ApplicationVirtualPath = "~" + Request.CurrentExecutionFilePath + ((Request.ServerVariables["Query_String"] == "") ? "" : ("?" + Request.ServerVariables["Query_String"]));
                string ConnString = "KPI_Security";
                string SqlCmd = "KPISecurity2018.Application_CheckAccess";
                SqlConnection oSqlConnection = new SqlConnection(System.Configuration.ConfigurationManager.ConnectionStrings[ConnString].ConnectionString);
                SqlCommand oSqlCommand = new SqlCommand(SqlCmd, oSqlConnection);

                try
                {
                    oSqlConnection.Open();
                    oSqlCommand.CommandType = CommandType.StoredProcedure;
                    SqlCommandBuilder.DeriveParameters(oSqlCommand);
                    oSqlCommand.Parameters["@AUID"].Value = Session["KPISystemUserID"];
                    //Response.Write("KPISystemUserID: " + Session["KPISystemUserID"].ToString() + "<br/>");
                    oSqlCommand.Parameters["@NodeAddress"].Value = ApplicationVirtualPath;
                    //Response.Write("Virtual Path: " + ApplicationVirtualPath + "<br/>");
                    oSqlCommand.ExecuteNonQuery();

                    TempData["UserAccessLevel"] = oSqlCommand.Parameters["@Level"].Value;
                    TempData["UserAdminURL"] = oSqlCommand.Parameters["@AdminURL"].Value;
                    TempData["HelpFileURL"] = oSqlCommand.Parameters["@HelpURL"].Value;
                    TempData["KeyType"] = oSqlCommand.Parameters["@KEID"].Value;
                    //Response.Write("CheckAccessKLeyType: " + TempData.Peek("KeyType").ToString() + "<br/>");
                    TempData["CompanyLogo"] = oSqlCommand.Parameters["@CompanyLogo"].Value.ToString().Replace("~", "");
                    TempData["ApplicationName"] = oSqlCommand.Parameters["@ApplicationName"].Value;

                    oSqlCommand.Dispose();
                    oSqlConnection.Close();
                    Session["OBLoggedIn"] = true;

                    switch (Convert.ToInt16(TempData.Peek("KeyType")))
                    {
                        case 1010:
                            TempData["LevelMin"] = 50;
                            break;
                        case 1020:
                            TempData["LevelMin"] = 10;
                            break;
                        case 1030:
                            TempData["LevelMin"] = 10;
                            break;
                        case 1060:
                            TempData["LevelMin"] = 10;
                            break;
                        case 6010:
                            TempData["LevelMin"] = 10;
                            break;
                        default:
                            TempData["LevelMin"] = 10;
                            break;
                    }

                }
                catch (Exception ex)
                {
                    oSqlCommand.Dispose();
                    oSqlConnection.Close();
                    ViewBag.Error = ex.Message;
                    return View();
                    
                }
            }
            Guid myid = Guid.Parse(Session["KPISystemUserID"].ToString());
            short myshort = short.Parse(TempData.Peek("KeyType").ToString());
            if (referrer == "Index2" || referrer == "Details")
            {

                spOwnerBilling_Result r1 = db.spOwnerBilling(myshort, myid, OB.MMMCU, OB.OBSeqNoId).First();

                return View(r1);

            }
            else
            {



                dynamic showMessageString = string.Empty;


                switch (buttontype)
                {
                    case "Cancel":
                        showMessageString = new
                        {
                            param1 = 200,
                            param2 = "Cancelled"

                        };
                        break;
                    case "Save":
                    case "Submit Pencil Draft":
                    case "Submit Final":
                        using (var con = new SqlConnection

                    (ConfigurationManager.ConnectionStrings["App_OwnerBilling"].ConnectionString))

                        {

                            var cmd = new SqlCommand("OwnerBilling2017.OwnerBilling", con);

                            cmd.CommandType = CommandType.StoredProcedure;

                            cmd.Parameters.Add(new SqlParameter("@OBMCU", SqlDbType.VarChar)).Value = OB.MMMCU;

                            cmd.Parameters.Add(new SqlParameter("@OBSeqNo", SqlDbType.SmallInt)).Value = OB.OBSeqNoId;

                            cmd.Parameters.Add(new SqlParameter("@OBApplicationNo", SqlDbType.SmallInt)).Value = OB.OBApplicationNo;

                            if (buttontype == "Submit Pencil Draft")
                            {
                                cmd.Parameters.Add(new SqlParameter("@OBStatus", SqlDbType.TinyInt)).Value = 10;
                            }
                            else if (buttontype == "Submit Final")
                            {
                                cmd.Parameters.Add(new SqlParameter("@OBStatus", SqlDbType.TinyInt)).Value = 20;
                            }
                            else
                            {
                                cmd.Parameters.Add(new SqlParameter("@OBStatus", SqlDbType.TinyInt)).Value = OB.OBStatus;
                            }


                            cmd.Parameters.Add(new SqlParameter("@OBSubmitDate", SqlDbType.Date)).Value = OB.OBSubmitDate;

                            cmd.Parameters.Add(new SqlParameter("@OBApproveDate", SqlDbType.Date)).Value = OB.OBApproveDate;

                            cmd.Parameters.Add(new SqlParameter("@OBSubWorkEstimate", SqlDbType.Money)).Value = OB.OBSubWorkEstimate;

                            cmd.Parameters.Add(new SqlParameter("@OBClarkWorkEstimate ", SqlDbType.Money)).Value = OB.OBClarkWorkEstimate;

                            cmd.Parameters.Add(new SqlParameter("@OBOwnerRetentionEstimate", SqlDbType.Money)).Value = OB.OBOwnerRetentionEstimate;

                            cmd.Parameters.Add(new SqlParameter("@OBSubRetentionEstimate", SqlDbType.Money)).Value = OB.OBSubRetentionEstimate;

                            cmd.Parameters.Add(new SqlParameter("@OBSubWorkFinal", SqlDbType.Money)).Value = OB.OBSubWorkFinal;

                            cmd.Parameters.Add(new SqlParameter("@OBClarkWorkFinal", SqlDbType.Money)).Value = OB.OBClarkWorkFinal;

                            cmd.Parameters.Add(new SqlParameter("@OBOwnerRetentionFinal", SqlDbType.Money)).Value = OB.OBOwnerRetentionFinal;

                            cmd.Parameters.Add(new SqlParameter("@OBSubRetentionFinal", SqlDbType.Money)).Value = OB.OBSubRetentionFinal;

                            cmd.Parameters.Add(new SqlParameter("@OBRemark", SqlDbType.VarChar)).Value = OB.OBRemark;

                            cmd.Parameters.Add(new SqlParameter("@UserName", SqlDbType.VarChar, 100)).Value = Session["KPISystemUserName"].ToString();

                            cmd.Parameters.Add(new SqlParameter("@Option", SqlDbType.Int)).Value = 70;

                            try

                            {

                                if (con.State != ConnectionState.Open)

                                    con.Open();

                                cmd.ExecuteNonQuery();
                                showMessageString = new
                                {
                                    param1 = 200,
                                    param2 = "success"

                                };

                            }
                            catch (Exception ex)
                            {
                                showMessageString = new
                                {
                                    param1 = 404,
                                    param2 = ex.Message
                                };

                            }

                            finally

                            {

                                if (con.State != ConnectionState.Closed)

                                    con.Close();

                            }

                        }
                        return Json(showMessageString, JsonRequestBehavior.AllowGet);
                    //break;


                    case "Skip This Month":

ownerbilling2018/Views/OwnerBilling/Index.cshtml
@model PagedList.IPagedList<ownerbilling2018.Models.spOwnerBilling_Result>
@using PagedList.Mvc;

<style>

    .headersubmit:hover, #headersubmit:hover {
        cursor: pointer;
    }
</style>
@{
    if (ViewBag.Error == null)
    {
        <div class="masterDivDetail">



            @Html.Partial("ReqDetail", new ViewDataDictionary { { "pagelevel", "Project" } })

            @{
                MvcForm form;
                if (Request.QueryString["AppID"] != null)
                {
                    form = Html.BeginForm("Default", "OwnerBilling", new { AppID = Request.QueryString["AppID"].ToString() }, FormMethod.Post, new { name = "obformfilter", id = "obformfilter" });
                }
                else
                {
                    form = Html.BeginForm("Default", "OwnerBilling", FormMethod.Post, new { name = "obformfilter", id = "obformfilter" });
                }
                using (form)
                {
                    @Html.AntiForgeryToken()
                    <div style="width:100%;text-align:center;margin-bottom:0px;background-color:#f1f1f1;display:block;float:left;clear:both;">
                        <div style="margin:0 auto;margin-left:auto;margin-right:auto;border:0px solid blue;width:auto;padding-bottom:5px;">

                            @{if (Convert.ToInt32(TempData.Peek("KeyType").ToString()) == 9999)
                                {
                                    <div style="margin-left:4px;margin-right:4px;display:inline-block;white-space: nowrap;"><div class="searchdiv" style="">Company:</div><div class="searchdiv"> @Html.DropDownList("Companies", "* ALL")</div></div>
                                }
                            }

                            <div style="margin-left:4px;margin-right:4px;display:inline-block;white-space: nowrap;"><div class="searchdiv" style="">Region: </div><div class="searchdiv">@Html.DropDownList("Regions", "* ALL") </div></div>
                            <div style="margin-left:4px;margin-right:4px;display:inline-block;white-space: nowrap;"><div class="searchdiv" style="">Project No / Name:</div><div class="searchdiv"> @Html.TextBox("searchString", ViewBag.CurrentFilter as string, new { style = "text-align:left;width:240px;" })</div></div>
                            <input type="hidden" id="sortOrder" name="sortOrder" value="@ViewBag.CurrentSort" />
                            <input type="hidden" id="whichpagenum" name="whichpagenum" value="" />
                            <input type="hidden" id="whichpage" name="whichpage" value="" />
                            <input type="hidden" name="myaction" value="Default" />



                        </div>
                    </div>
                }
            }
            <script>

        $(document).ready(function () {


            $('.joblink').click(function () {
                var mystring = this.id;
                var mystring2 = $(this).text();
                $('#MMMCU').val(mystring.replace("link-", ""));
                $('#obform').submit();
            });

            $('#sortlink1').click(function () {
                $('#sortOrder').val("@ViewBag.NameSortParm");
                document.forms[0].submit();
            });
             $('#sortlink2').click(function () {
                $('#sortOrder').val("@ViewBag.DateSortParm");
                document.forms[0].submit();
            });
            $('#sortlink3').click(function () {
                $('#sortOrder').val("@ViewBag.AppSortParm");
                document.forms[0].submit();
            });

            $('#pagelinkFirst').click(function () {
                $('#whichpage').val("First");
                document.forms[0].submit();
            });
            $('#pagelinkNext').click(function () {
                $('#whichpage').val("Next");
                $('#whichpagenum').val(@ViewBag.pagenum);
                document.forms[0].submit();
            });
            $('#pagelinkLast').click(function () {
                $('#whichpage').val("Last");
                document.forms[0].submit();
            });
            $('#pagelinkPrevious').click(function () {
                $('#whichpage').val("Previous");
                $('#whichpagenum').val(@ViewBag.pagenum);
                document.forms[0].submit();
            });

            $('#MyPagedList').change(function () {
                var pageName = $('#MyPagedList').find(":selected").text();
                $('#whichpagenum').val(pageName);
                document.forms[0].submit();
            });

       });

        $('#searchString').change(function () { this.form.submit(); });

        $(function () {
            $('#Companies').change(function () {
                $('#obformfilter').submit();

            });
        });

        $(function () {
            $('#Regions').change(function () {
                this.form.submit();
            });
        });

            </script>

            <style type="text/css">

                th {
                    text-align: center;
                }
            </style>

            @{
                MvcForm form2;
                if (Request.QueryString["AppID"] != null)
                {
                    form2 = Html.BeginForm("Default", "OwnerBilling", new { AppID = Request.QueryString["AppID"].ToString() }, FormMethod.Post, new { name = "obform", id = "obform" });
                }
                else
                {
                    form2 = Html.BeginForm("Default", "OwnerBilling", FormMethod.Post, new { name = "obform", id = "obform" });
                }
                using (form2)
                {
                    @Html.AntiForgeryToken()
                    <input type="hidden" id="MMMCU" name="MMMCU" value="" />
                    <input type="hidden" id="myaction" name="myaction" value="Index2" />
                    <table class="table kpipager1" cellspacing="3" cellpadding="3">
                        <tr>
                            <th>


                                <a class="headersubmit" id="sortlink1">Project Name</a>

                            </th>
                            <th>
                                <a class="headersubmit" id="sortlink2">Requisition Date</a>

                            </th>
                            <th>
                                <a class="headersubmit" id="sortlink3">App No</a>

                            </th>
                            <th>
                                Estimate Requisition
                            </th>
                            <th>
                                Final Requistion
                            </th>


                        </tr>
                        @{ if (Model.TotalItemCount == 0)
                            {
                                <tr><td colspan="5" style="color:red;" align="center">No Projects Found!</td></tr>
                            }
                            else
                            {
                                foreach (var item in Model)
                                {
                                    <tr>
                                        <td>

                                            <a class="joblink" id="link-@item.MMMCU.Trim()">@item.jobdescription</a>

                                        </td>
                                        <td align="center">
                                            @string.Format("{0:MM/dd/yyyy}", item.OBRequisitionDate)
                                        </td>
                                        <td align="center">
                                            @Html.DisplayFor(modelItem => item.OBApplicationNo)
                                        </td>

                                        <td align="right">

                                            @string.Format("{0:C}", item.OBTotalEstimate)
                                        </td>
                                        <td align="right">
                                            @string.Format("{0:C}", item.OBTotalFinal)
                                        </td>

                                    </tr>
                                }
                            }


                        }

                    </table>
                }
            }
            <br />
            @if (Convert.ToInt32(ViewBag.mypagecount) > 1)
            {

            
            <div class="pagerfooter">

                
                    @if (Convert.ToInt32(ViewBag.pagenum) != 1)
                    {


                        <a class="headersubmit pagerlink" id="pagelinkFirst">&lt;&lt;First</a>

                        <a class="headersubmit pagerlink" id="pagelinkPrevious">&lt;Prev</a>
                    }
                

               @Html.DropDownList("MyPagedList", new SelectList(ViewBag.list, "Text", "Value", ViewBag.pagenum.ToString()), new { sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter, currentFilterR = ViewBag.CurrentFilterR, currentFilterC = ViewBag.CurrentFilterC })

                of @Model.PageCount

                
                    @if (Convert.ToInt32(ViewBag.pagenum) < @Model.PageCount)
                    {
                        <a class="headersubmit pagerlink" id="pagelinkNext">Next&gt;</a>

                        <a class="headersubmit pagerlink" id="pagelinkLast">Last&gt;&gt;</a>
                    }
                
            </div>
            }
        </div>
                            }
                            else
                            {
                                Html.Partial("NoAccess");
                            }
}

ownerbilling2018/Views/OwnerBilling/Index2.cshtml
@model IEnumerable<ownerbilling2018.Models.spOwnerBilling_Result>
@using System.Web.Mvc.Html;

@if (ViewBag.Message != null)
{
    <script type="text/javascript">

        window.onload = function () {
            alert("@ViewBag.Message");
        };

    </script>
}

<script type="text/javascript">

    $(document).ready(function () {
        $("#OBRequisitionDate").val("");
        $(function () { $("#OBRequisitionDate").datepicker({ showOn: "button", buttonImage: "/Images/TextBoxBackground/calendar.gif", buttonImageOnly: true, buttonText: "Select date" }); });

        $('.joblink').click(function () {

            $(this).parents('form:first').submit();

        });

        $('#goback').click(function () {

            $("#gobackform").submit();

        });

        $('.deletelink').click(function () {
            if (checkFormView("D") == true) {
                $(this).parents('form:first').submit();
            } else { return false; }
        });

    });

</script>

<div class="masterDivDetail" bla>

    @Html.Partial("ReqDetail", new ViewDataDictionary { { "pagelevel", "Requisition" }, { "JobNo", @Model.First().MMMCU }, { "JobDescription", @Model.First().jobdescription } })
    
    
    @{ 

        MvcForm form;
        if (Request.QueryString["AppID"] != null)
        {
            form = Html.BeginForm("Default", "OwnerBilling", new { AppID = Request.QueryString["AppID"].ToString() }, FormMethod.Post, new { id = "gobackform", name = "gobackform" });
        }
        else
        {
            form = Html.BeginForm("Default", "OwnerBilling", FormMethod.Post, new { id = "gobackform", name = "gobackform" });
        }



        using (form)
        {
        @Html.AntiForgeryToken()
        <a class="headersubmit backlink" id="goback">Back</a>
        <input type="hidden" id="myaction" name="myaction" value="Default" />
            }
        }
    <table class="table kpipager2">
        <tr id="headerrow">
            <th>
                Requisition Date
            </th>
            <th>
                App No
            </th>
            <th>
                Status
            </th>
            <th>
                Estimate Requisition
            </th>
            <th>
                Submit Date
            </th>
            <th>
                Approve Date
            </th>
            <th>
                Final Requisition
            </th>
            <th>
                Due Date
            </th>
            <th>
                Date Paid
            </th>
            <th>
                Action
            </th>
        </tr>

        @foreach (var item in Model.Where(x => x.OBRequisitionDate != null))
        {
            <tr id="row-@item.OBSeqNoId">

                <td>

                    @{ 

                        MvcForm form2;
                        if (Request.QueryString["AppID"] != null)
                        {
                            form2 = Html.BeginForm("Default", "OwnerBilling", new { AppID = Request.QueryString["AppID"].ToString() }, FormMethod.Post, new { id = "detailform" + @item.OBSeqNoId, name = "detailform" + @item.OBSeqNoId });
                        }
                        else
                        {
                            form2 = Html.BeginForm("Default", "OwnerBilling", FormMethod.Post, new { id = "detailform" + @item.OBSeqNoId, name = "detailform" + @item.OBSeqNoId });
                        }

                        using (form2)
                        {
                        @Html.AntiForgeryToken()
                        <input type="hidden" name="MMMCU" value="@item.MMMCU" />
                        <input type="hidden" name="OBSeqNoId" value="@item.OBSeqNoId" />
                        <input type="hidden" name="myaction" value="Details" />
                        <a class="joblink" id="link-@item.OBSeqNoId"> @string.Format("{0:MM/dd/yyyy}", item.OBRequisitionDate)</a>
                            }
                        }
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.OBApplicationNo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.OBStatusDescription)
                </td>
                <td align="right">

                    @string.Format("{0:C0}", item.OBTotalEstimate)
                </td>
                <td>
                    @string.Format("{0:MM/dd/yyyy}", item.OBSubmitDate)
                </td>
                <td>
                    @string.Format("{0:MM/dd/yyyy}", item.OBApproveDate)
                </td>
                <td align="right">
                    @string.Format("{0:C0}", item.OBTotalFinal)
                </td>
                <td>
                    @string.Format("{0:MM/dd/yyyy}", item.G4DueDate)
                </td>
                <td>
                    @string.Format("{0:MM/dd/yyyy}", item.KDOwnerPaymentReceivedDate)
                </td>
                <td>
                    @{
                        if (item.OBStatus < 10 && Convert.ToInt32(TempData.Peek("UserAccessLevel").ToString()) >= Convert.ToInt32(TempData.Peek("LevelMin").ToString()))

                        {

                            

                            using (Ajax.BeginForm("Default", new { @MMMCU = item.MMMCU, @OBSeqNoId = item.OBSeqNoId }, new AjaxOptions() { HttpMethod = "POST", OnFailure = "OnFailure", OnSuccess = "OnSuccessDelete" }, new { id = "deleteform" + @item.OBSeqNoId, name = "deleteform" + @item.OBSeqNoId }))
                            {
                                        @Html.AntiForgeryToken()
                                        <input type="hidden" name="MMMCU" value="@item.MMMCU" />
        
                                        <input type="hidden" name="myaction" value="Delete" />
        
                                        <input type="hidden" name="OBSeqNoId" value="@item.OBSeqNoId" />
        
                                        <a class="deletelink">Delete</a>
                        }
                    }
                    }
                </td>

            </tr>
                        }

    </table>

    <div class="form-horizontal">

        <div class="form-group">

            <div class="col-md-10">

                @{

                    MvcForm form3;
                    if (Request.QueryString["AppID"] != null)
                    {
                        form3 = Html.BeginForm("Default", "OwnerBilling", new { AppID = Request.QueryString["AppID"].ToString() }, FormMethod.Post, new { id = "oldform", name = "oldform" });
                    }
                    else
                    {
                        form3 = Html.BeginForm("Default", "OwnerBilling", FormMethod.Post, new { id = "oldform", name = "oldform" });
                    }
                    using (form3)
                    {
                @Html.AntiForgeryToken()
                <input type="hidden" id="oldMMMCU" name="MMMCU" value="@Model.First().MMMCU" class="btn btn-default" />
                <input type="hidden" id="oldjobdescription" name="jobdescription" value="@Model.First().jobdescription" class="btn btn-default" />
                <input type="hidden" id="OBSeqNoId" name="OBSeqNoId" class="btn btn-default" />
                <input type="hidden" id="referrer" name="referrer" value="Index2" />
                <input type="hidden" id="myaction" name="myaction" value="Edit" />
                }
                }

                @{

                    if (Convert.ToInt32(TempData.Peek("UserAccessLevel").ToString()) >= Convert.ToInt32(TempData.Peek("LevelMin").ToString()))
                    {


                        using (Ajax.BeginForm("Default", null, new AjaxOptions() { HttpMethod = "POST", OnFailure = "OnFailure", OnSuccess = "OnSuccess" }, new { id = "newform", name = "newform" }))
                        {

                @Html.AntiForgeryToken()
                <div id="reqdate">Requisition Date:</div>
                @Html.TextBoxFor(model => model.First().OBRequisitionDate, new { @value = "", @style = "width:80px;", data_val_date = "Not a correct date format." });
                @Html.ValidationMessageFor(model => Model.First().OBRequisitionDate, "", new { @class = "text-danger" })
                <input type="hidden" id="MMMCU" name="MMMCU" value="@Model.First().MMMCU" class="btn btn-default" />
                <input type="hidden" id="myaction" name="myaction" value="CreateNew" class="btn btn-default" />
                <input id="newreq" type="submit" value="Create" class="btn btn-default" onclick="javascript:return verifyFields($('#OBRequisitionDate'),'OBRequisitionDate',true);" />
}
}
                }

                <script type="text/javascript">
                    function OnSuccess(data) {
                        if (data.param1 == "404") {
                            alert(data.param2);
                        } else {

                            $("#OBSeqNoId").val(data.param2);
                            $("#oldform").submit();
                        }

                    }
                    function OnFailure(data) {
                        alert(data.param2);
                    }

                    function OnSuccessDelete(data) {
                        if (data.param1 == "404") {
                            alert("404 error: " + data.param2);
                        } else {

                            document.getElementById(data.param2).style.display = "none";

                        }
                    }

                </script>

            </div>

        </div>

    </div>

</div>

ownerbilling2018/Views/OwnerBilling/NoAccess.cshtml
<div class="masterDivDetail" style="">
    <table width="100%" style="height:600px; background-color:White;">
        <tr valign="middle">
            <td align="center">


                ERROR: @ViewBag.Error

            </td>
        </tr>
    </table>
</div>

ownerbilling2018/Views/OwnerBilling/ReqDetail.cshtml
<div style="font-size:20px;width:100%;border:0px solid blue;text-align:center;float: left;display:block;clear:both;">
    @{


        switch ((string)@ViewBag.pagelevel)
        {
            case "Project":
                <span style="font-weight:bold;">Projects</span>
                break;
            case "Requisition":

                <span style="font-weight:bold;">Requisitions:</span><span>@ViewBag.JobDescription</span>
                break;
            case "Detail":
                <span style="font-weight:bold;">Requisition Detail:</span><span>@ViewBag.JobDescription</span>
                break;
        }
    }
</div>